MDTZ-1153: Update `/entities` endpoint to take user ID from query par…
atlassian-labs/figma-for-jira pull request #137
Opened 2023-10-31 22:26 UTC by akostevich-atlassian

## Changes

- **refactor:** Updates `/entities` endpoint to take user ID from query parameters.
- **refactor:** Removes `extractUserIdFromHeadersMiddleware` as unused.

2023-10-31 23:52 UTC, stannnous requested changes
Bug: You'll also have to update the action template URLs in `atlassian-connect.ts`

2023-10-31 23:53 UTC, stannnous commented on src/web/middleware/jira/extract-user-id-from-headers-middleware.ts
One less middleware 🍾

2023-11-01 00:43 UTC, akostevich-atlassian commented
> Bug: You'll also have to update the action template URLs in `atlassian-connect.ts`

Oh, my goldfish memory in action. Thank you, Sam, for your careful review and double reminder about this change!

2023-11-01 03:16 UTC, stannnous approved these changes

2023-11-01 03:33 UTC, merged