[DRAFT] MDTZ-1749: Implement the simplified `jiraDesignInfoProvider` module
atlassian-labs/figma-for-jira pull request #235
Opened 2024-05-29 04:28 UTC by akostevich-atlassian

### Changes

- **feat:** Implement _Actions_ of the simplified `jiraDesignInfoProvider` module specification: `getEntityByUrl`, `onEntityAssociated`, `onEntityDisassociated`. These _Actions_ represent a replacement for the existing `associateEntity` and `disassociateEntity`, which will be removed from the app when the rollout of the simplified `jiraDesignInfoProvider` module is completed.

2024-05-30 07:11 UTC, francox9 commented
🔥

2024-05-30 10:30 UTC, stannnous requested changes
Great work. Just the HTTP method change for getEntityByUrl

2024-05-30 10:30 UTC, stannnous commented on README.md
> +   curl --request PUT \
Did we agree on POST for this action?

2024-05-30 10:30 UTC, stannnous commented on src/web/routes/entities-v2/entities-router.ts
> +entitiesRouterV2.put(
post

2024-05-30 10:30 UTC, stannnous commented on src/web/routes/entities-v2/schemas.ts
> +						ati: { type: 'string', pattern: 'ati:cloud:jira:issue' }, // Handle only associations with a Jira Issue.
Nice @akostevich-atlassian+++++

2024-05-30 10:30 UTC, stannnous commented on src/web/routes/entities-v2/entities-router.ts
> +			getDesignByUrlForBackfillUseCase
To clarify: the Figma app will return the minimal design for the backfill use case which will be ingested with the issue association by Jira and the app will then async send the full design (without the issue association). This is temporary until the backfill use case can be removed after the Figma widget is updated.

2024-05-30 10:37 UTC, akostevich-atlassian commented on README.md
> +   curl --request PUT \
We did -- I need to fix this.

2024-06-18 05:37 UTC, stannnous approved these changes

2024-07-10 13:59 UTC, knguyen-figma approved these changes

2024-07-11 01:43 UTC, merged